version: "3"
services:
    web:
        image: nginx:1.21.6
        container_name: ${PROJECT}_nginx
        restart: always
        links:
            - site
        volumes:
            - ./server.conf:/etc/nginx/conf.d/default.conf
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./data/logs:/logs
            - ..:/project

    site:
        build:
            dockerfile: Dockerfile.site
            context: .
        container_name: ${PROJECT}_site
        restart: always
        environment:
            - PROJECT=${PROJECT}
            - ADMIN_TOKEN=${PROJECT_ADMIN_TOKEN}
        volumes:
            - ..:/project

networks:
    default:
        name: ${PROJECT}_network
        driver: bridge
